### ISSUE TITLE
knife.rb proxy settings not honored

### ISSUE THREAD

**Issue by jblaine** [chef/knife-openstack#137]
knife-openstack 0.10.0 (at least) is not making use of knife.rb proxy settings and is instead making use of shell environment variables:

    # knife.rb
    # ...
    no_proxy '*.our.com" # Being ignored!
    http_proxy 'http://whatever.our.com:80' # Probably this too
    https_proxy 'http://whatever.our.com:80' # and this too
    # ...

This is what happens:

    % knife openstack server list
    FATAL: Connection failure, please check your OpenStack authentication URL.
    % unset http_proxy
    % unset https_proxy
    % unset HTTP_PROXY
    % knife openstack server list
    <works fine!>

**Comment by jjasghar** [comment]
I believe this is resolved, please reopen is it is still an issue, the new gem has knife-cloud underneath it that should deal with this.
