### ISSUE TITLE
knife openstack floatip <args> ?

### ISSUE THREAD

**Issue by jblaine** [chef/knife-openstack#138]
I'm no Openstack guru. I'm a user of a corporate Nebula appliance I have no administrative control over.

In order to use 'knife openstack server create' in our environment, I had to pre-allocate a floating IP address via the Nebula web UI and use '--bootstrap-network external'. Fine, but it seemed odd to me that there was no 'knife openstack' command to perform floating IP ops.

I envision:

```
knife openstack floatip create
knife openstack floatip list
knife openstack floatip associate --address <addr> --instance <instance name>
knife openstack floatip disassociate --address <addr> --instance <instance name>
knife openstack floatip delete
knife openstack floatip release (alias for delete)
```

No?

**Comment by jjasghar** [comment]
https://github.com/chef/knife-openstack/pull/167

**Comment by jjasghar** [comment]
https://github.com/chef/knife-openstack/pull/170

**Comment by jjasghar** [comment]
So so so close, @dschlenk and @jblaine

**Comment by jblaine** [comment]
hi5
