### ISSUE TITLE
no support for multi-region - major blocker

### ISSUE THREAD

**Issue by boris-deschenes** [chef/knife-openstack#139]
Hi guys,

We operated a cloud with multiple regions (as any cloud providers would do) and this plugin is lacking the feature of being able to specify a cloud region... since there is no way to specify a cloud region the knife-openstack plugin is currently unusable on any real-world, multi-region clouds...

since fog, the underlying lib, supports multiple regions, it's probably only a matter of handling the:

knife[:openstack_region] = "XXX"

from the knife.rb and passing it to fog.

Again, unless there is support for multi region in this plugin, there is no way to use this on a multi-region openstack cloud, which is a major blocker IMHO.

**Comment by jjasghar** [comment]
I believe this is resolved, please reopen is it is still an issue.
