### ISSUE TITLE
Get ERROR: You have either requested an invalid floating IP address or none are available.

### ISSUE THREAD

**Issue by rkatti** [chef/knife-openstack#149]
I get this error when running following command : 

knife openstack server create -f 3 --image  e60659e8-ec3b-4074-acde-2a545bf9a76d   -S pertest2 -N ct11  --ssh-user ubuntu --bootstrap-network nova_fixed --identity-file ~/Downloads/pertest2.pem  -c ~/.chef/knife-test.rb  --network-id 2d0edb26-479c-4d07-a391-5876efafc818   -a 10.1.1.225

ERROR: You have either requested an invalid floating IP address or none are available.

If I run above without -a option it works and the VM gets 10.1.1.225 ip assigned.

Any idea why this is happening ?

**Comment by jjasghar** [comment]
You probably didnt have any floating IPs assigned to your account. Please update the gem and see if this is still an issue. If it is please reopen.
