### ISSUE TITLE
knife openstack fails to bootstrap server

### ISSUE THREAD

**Issue by linxit** [chef/knife-openstack#151]
The ssh connection to the floating IP fails, eventually timing out. However, "knife bootstrap..." works fine afterwards, so I know the ssh key's correct. So it creates the server OK, but then I get this:
```
[andyw@chef12-wks chef-repo]$ knife openstack server create --flavor bc2f3498-748c-4a69-a95f-64d73fa4d579 \ 
--image 515fa5ae-3b8a-4a36-a722-d698f553c69a -T dev --network-ids 55aec44d-7b3b-4c01-b382-7d3a63ab77fd \ 
--openstack-floating-ip -Z dev-test -G mgmt-dev,default -N cc-dev --ssh-user stack --sudo

Waiting for server [wait time = 600]...................
Instance ID        57789edb-2e9e-455e-a0df-6dc31fab6016
Name               cc-dev
Flavor             bc2f3498-748c-4a69-a95f-64d73fa4d579
Image              515fa5ae-3b8a-4a36-a722-d698f553c69a
Keypair            aw-test
State              ACTIVE
Availability Zone  dev-test
Floating IP Address: 10.239.0.22
Bootstrapping the server by using bootstrap_protocol: ssh and image_os_type: linux

Waiting for sshd to host (10.239.0.22)....done
Connecting to 10.239.0.22
Failed to authenticate stack - trying password auth
Enter your password:
FATAL: Authentication Failed during bootstrapping. Authentication failed for user stack@10.239.0.22@10.239.0.22.
```
This is on Rackspace Private Cloud, by the way, so the user has no password, and can only login with the private key. The obvious error is the username stack@10.239.0.22@10.239.0.22, but I haven't configured it like that anywhere, and on the command line I just use '--ssh-user stack'. I don't even specify the floating IP - it picks one itself from the available pool.

Right after this, with no changes to anything I can run knife bootstrap:
```
[andyw@chef12-wks chef-repo]$ knife bootstrap 10.239.0.22 -x stack -i aw-test -N cc-dev --sudo
Connecting to 10.239.0.22
10.239.0.22 Installing Chef Client...
10.239.0.22 --2014-12-24 15:12:17--  https://www.opscode.com/chef/install.sh
10.239.0.22 Resolving www.opscode.com... 184.106.28.91
10.239.0.22 Connecting to www.opscode.com|184.106.28.91|:443... connected.
10.239.0.22 HTTP request sent, awaiting response... 200 OK
10.239.0.22 Length: 18285 (18K) [application/x-sh]
10.239.0.22 Saving to: “STDOUT”
10.239.0.22
100%[======================================>] 18,285      --.-K/s   in 0.001s
10.239.0.22
10.239.0.22 2014-12-24 15:12:18 (17.5 MB/s) - written to stdout [18285/18285]
10.239.0.22
10.239.0.22 Downloading Chef 11 for el...
etc etc
```
I'm using a local chef-server, version 12.0.0-1 and chefdk-0.3.5-1 on the workstation, with knife-openstack 1.0.0.

**Comment by linxit** [comment]
Hi, did you have a chance to look at this yet? Still causing me problems.

**Comment by jjasghar** [comment]
Sorry no, i still havent had the cycles to create a multi-region instance. i attempted to with virtualbox on my laptop; and it blew up in my face. Updates when i have them.

**Comment by linxit** [comment]
Different problem I think - my issue was with the bootstrap process inserting the floating IP address twice and trying to ssh to stack@<ip_address>@<ip_address>

**Comment by jjasghar** [comment]
Ah yeah, sorry.

Nope, i havent looked at this at all it's probably due to your knife.rb settings though, i swear i've seen this issue before.

A fixed it by reconfirming my knife.rb settings. can you scrub them and put it here?

**Comment by linxit** [comment]
That's what I was afraid of, but I can't see anything in there that would cause it. Here it is anyway:

current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "andyw"
client_key               "#{current_dir}/andyw.pem"
validation_client_name   "myco-validator"
validation_key           "#{current_dir}/myco-validator.pem"
chef_server_url          "https://10.239.0.20/organizations/myco"
cache_type               'BasicFile'
cache_options( :path => "#{ENV['HOME']}/.chef/checksums" )
cookbook_path            ["#{current_dir}/../cookbooks"]
cookbook_copyright "MyCo Ltd."
cookbook_email     "andy.wallace@myco.com"
cookbook_license   "none"
verify_api_cert false
ssl_verify_mode :verify_none

knife[:openstack_auth_url] = "http://172.29.236.10:5000/v2.0/tokens"
knife[:openstack_username] = "myco-admin"
knife[:openstack_password] = "mysecret"
knife[:openstack_insecure] = true
knife[:openstack_endpoint_type] = "internalURL"
knife[:openstack_ssh_key_id] = "aw-test"

**Comment by linxit** [comment]
It wasn't the knife.rb file, but it was me - I missed out the --identity-file option, so it was defaulting to using my ~/.ssh/id_rsa (which was in a valid key-pair, but not the right one). I ran knife openstack with -V -V and traced the key signature. I've got it working now, thanks.

The error message at the end with the two IP addresses is a bit misleading though - sent me off in the wrong direction anyway.

**Comment by spuder** [comment]
+1 I'm also getting this error

It is trying to log into ubuntu@10.200.1.155@10.200.1.155

size=medium
name=spentest7
knife openstack server create -f m1.${size} -I 'Ubuntu 14.04 Trusty' -N ${name} -S 'nd_rsa' -x ubuntu -a -i ~/.ssh/nd_rsa


You have to add the -i option to the knife command
