### ISSUE TITLE
support multi region for OpenStack

### ISSUE THREAD

**Issue by bassthumper** [chef/knife-openstack#152]
Opening a new issue per

I’ve reviewed and tried what was found in the issue #148 but am not able to get multi-region support to work (within Internap's Openstack implementation).   Please point out what I am doing wrong.

Details:
I have set the value in my knife.rb as noted in #148, and confirmed that knife.rb is being used by my script (inapt.sh).   But I still get an error indicating that I need to pick from one of the Internap regions (da01, ne01, ams01).   

Here is output from my terminal session...

MyMac:/Users/bassthumper/downloads $cat /Users/bassthumper/.chef/knife.rb
knife[:openstack_region] = "da01"

MyMac:/Users/bassthumper/downloads $cat inap2.sh
knife openstack flavor list -A api-53b49c64c939f -T inap-10366 -K cf117ef5e02c6f4201c98ade4a974f99 --openstack-api-endpoint https://identity.api.cloud.iweb.com/v2.0/tokens -V 

MyMac:/Users/bassthumper/downloads $./inap2.sh
INFO: Using configuration from /Users/bassthumper/.chef/knife.rb
ERROR: Fog::Errors::NotFound: Multiple regions available choose one of these 'da01,ne01,ams01'

**Comment by jjasghar** [comment]
Awesome, thanks for this report. It's high on the priority list as soon as i can get a multi-region backend.

Devstack is looking more and more like the option for me :-/

**Comment by jjasghar** [comment]
Any chance you can do it with the -VV flag?

**Comment by jjasghar** [comment]
I believe: https://github.com/jjasghar/knife-openstack/commit/2c1ad66e815f37b10f485cc2d82b5802e8e65f46 will fix this issue, it's with the above PR #159 also.

**Comment by jjasghar** [comment]
I believe this is resolved now, please reopen if this is still an issue.
