### ISSUE TITLE
handle_excon_exception: undefined method

### ISSUE THREAD

**Issue by olivernaaris** [chef/knife-openstack#153]
Hi!

I was using knife-openstack and got the following error:

olivern@ubuntu:~/pt-dev-cookbook$ knife openstack server list -VV
DEBUG: openstack_username oliver.naaris
DEBUG: openstack_auth_url http://10.147.51.26:5000/v2.0
DEBUG: openstack_tenant Live2
DEBUG: openstack_endpoint_type publicURL
DEBUG: openstack_insecure 
DEBUG: Using fog version: 1.27.0
/home/olivern/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/fog/service.rb:131:in `handle_excon_exception': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/olivern/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/fog/service.rb:123:in `rescue in block (2 levels) in <class:FogService>'
	from /home/olivern/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/fog/service.rb:115:in `block (2 levels) in <class:FogService>'
	from /home/olivern/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/server/list_command.rb:65:in `query_resource'
	from /home/olivern/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/list_resource_command.rb:35:in `execute_command'
	from /home/olivern/.chefdk/gem/ruby/2.1.0/gems/knife-cloud-1.0.1/lib/chef/knife/cloud/command.rb:51:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:38:in `load'
	from /usr/bin/knife:38:in `<main>'

**Comment by grizo** [comment]
I'm having the same issue against OpenStack stable (IceHouse).

**Comment by jjasghar** [comment]
Ideally this PR: https://github.com/chef/knife-openstack/pull/159 should resolve this; we've had some underlying gem updates that have caused some issues.

**Comment by jjasghar** [comment]
If this is still an issue please reopen this after the updating the gem.
