### ISSUE TITLE
Add ability to specify host when using the -Z flag to specify availability-zone

### ISSUE THREAD

**Issue by ihavegerms** [chef/knife-openstack#158]
Currently, you can specify the availability zone using the -Z flag, but you cannot specify the specific host you want the instance to land on. This isn't a major blocker considering you can disable nova-compute within that availability-zone on the hypervisors that you do not want the instance to land on... but that could get tedious if you have a large number of computes or a lot of individuals using the environment. 

If there are any questions or if I can provide any additional details that would assist in getting this added, please let me know. (and thanks for reading)

**Comment by jjasghar** [comment]
I believe this is out of scope for this gem. I agree this could be tedious, but you shouldn't be leveraging knife-openstack to pin point an install.

I'm going to close this as won't fix or support.  If you are willing to write the PR and show me an unintrusive patch to make this happen I'm willing to look at it, but I'd have to ask you to support this feature from then on.

**Comment by linxit** [comment]
No need to reopen this, but maybe it's worth documenting...

This is already supported, although I can't find it in the documentation anywhere. After a chat with Rackspace support, they suggested using -Z <availability-zone>:<compute-node>, and so far it's worked every time! First I tried it with the nova boot command, then after that using knife openstack server create. Both times the instance went onto the specified node.

Before that we'd just added two new nodes to the availability zone and nothing was getting installed on them, so I don't think it was a coincidence.

**Comment by linxit** [comment]
Actually it is documented:

http://docs.openstack.org/user-guide-admin/content/specify-host-to-boot-instances-on.html

Maybe it's a new feature?
