### ISSUE TITLE
both -F json ad --format json does not work

### ISSUE THREAD

**Issue by b-slim** [chef/knife-openstack#160]
Hi,
I want to get the summary of the `kinfe openstack create` as json object, thought using `-F json` or `--format json` will do so, but i do get the same output (without fromating)

**Comment by b-slim** [comment]
by the way i am using 
```
 gem list knife-openstack

*** LOCAL GEMS ***

knife-openstack (1.1.0)
```

**Comment by jjasghar** [comment]
I've confirmed that this is an issue. It seems that this is something that `knife-cloud` should control, being that it's the library that would `knife-openstack` would call. I'm opening an issue there.

**Comment by jjasghar** [comment]
I have opened: https://github.com/chef/knife-cloud/issues/91
