### ISSUE TITLE
openstack server create not working with floating ips

### ISSUE THREAD

**Issue by cmluciano** [chef/knife-openstack#162]
I can provision a server and get to the point where it is "waiting for sshd" but I can not get any further. 

I can also use ```knife bootstrap``` the normal way and bootstrap the machine

Commands passed:
```
knife openstack server create -a -f 2 -I "centos-6" --ssh-user "centos" --sudo -N "test-me" --secret-file "secrets_path" -r 'role[blah]' --openstack-ssh-key-id mykey
```

Config file:
```
knife[:openstack_auth_url] = "http://myip:5000/v2.0/tokens"
knife[:openstack_username] = "validuser"
knife[:openstack_password] = "validpass"
knife[:openstack_tenant] = "validten"
knife[:openstack_insecure] = true
knife[:openstack_region] = "RegionOne"
knife[:openstack_ssh_key_id] = "mykey"
```

Using pry I stepped through the code and get to  
```
line 109:   @bootstrapper.bootstrap in
knife-cloud-1.0.1/lib/chef/knife/cloud/server/create_command.rb
```

from here I dump the config and it seems to have my flaoting ip, but :openstack_floating_ip=>nil

result of config
``` 
:color=>true,
 :editor=>"vim",
 :disable_editing=>false,
 :format=>"summary",
 :ssh_user=>"centos",
 :ssh_port=>5986,
 :template_file=>false,
 :run_list=>["role[myrole]"],
 :first_boot_attributes=>{},
 :host_key_verify=>true,
 :auth_timeout=>25,
 :image_os_type=>"linux",
 :bootstrap_protocol=>"ssh",
 :server_create_timeout=>600,
 :delete_server_on_failure=>false,
 :chef_node_name_prefix=>"openstack",
 :private_network=>false,
 :openstack_floating_ip=>nil,
 :openstack_security_groups=>["default"],
 :bootstrap_network=>"public",
 :network=>true,
 :fog_version=>"",
 :openstack_insecure=>true,
 :image=>"centos-6",
 :flavor=>"2",
 :openstack_ssh_key_id=>"mykey",
 :openstack_username=>"myuser",
 :openstack_password=>"mypass",
 :openstack_tenant=>"myuser",
 :openstack_auth_url=>"http://myip:5000/v2.0/tokens",
 :use_sudo=>true,
 :chef_node_name=>"nodename",
 :secret_file=>"secretspath",
 :config_file=>"knife.rb",
 :ssh_password=>"password",
 :bootstrap_ip_address=>"ValidIPfromOPenstack"}
```

If I manually set the config for floating_ip config[:openstack_floating_ip] = "ipfromopenstack"

then continue in pry I stop here and halt
```
mixlib-cli-1.5.0/lib/mixlib/cli.rb @ line 156 Mixlib::CLI#initialize:

    151:       # Set the banner
    152:       @banner  = self.class.banner
    153:
    154:       # Dupe the class options for this instance
    155:       klass_options = self.class.options
 => 156:       klass_options.keys.inject(@options) { |memo, key| memo[key] = klass_options[key].dup; memo }
    157:
    158:       # If use_separate_defaults? is on, default values go in @default_config
    159:       defaults_container = if self.class.use_separate_defaults?
    160:                              @default_config
    161:                            else

[1] (pry) #<Chef::Knife::Bootstrap>: 0> continue

Waiting for sshd to host (9.75.205.208).........
```

**Comment by cmluciano** [comment]
cc\ @jjasghar

**Comment by siddheshwar-more** [comment]
@cmluciano @jjasghar 

`:openstack_floating_ip` option is only set when you use `-a <some-floating-ip>`  and in above command your specifying it like `-a` (i.e without any floating ip) this will choose any available floating_ip from floating_pool and hence `config[:openstack_floating_ip] is nil`

Now, Halt in `waiting for sshd to host ...`  is because of `config[:bootstrap_ip_address]`

As tcp_test_ssh uses `config[:bootstrap_ip_address]` as a host

So, Could you please also share what's the `config[:bootstrap_ip_address]` value at  

```
line 109:   @bootstrapper.bootstrap in
knife-cloud-1.0.1/lib/chef/knife/cloud/server/create_command.rb

```

**Comment by cmluciano** [comment]
@siddheshwar-more 

Here is more output from -VV

DEBUG: Bootstrap IP Address: 192.168.0.1
DEBUG: Bootstrapping the server...
Bootstrapping the server by using bootstrap_protocol: ssh and image_os_type: linux
Private IP Address: 10.0.0.92
DEBUG: Floating IP Address requested
Floating IP Address: 192.168.0.1

config :bootstrap_ip_address=>”192.168.0.1”

They match up but it just hangs

**Comment by cmluciano** [comment]
Not sure if this helps
```
 @protocol.send_bootstrap_command
```
Waiting for sshd to host (192.168.0.1)DEBUG: No ssh gateway found, making a direct connection

**Comment by cmluciano** [comment]
Stepping through to the end leaves me hanging at this line in /mixlib-cli-1.5.0/lib/mixlib/cli.rb @ line 156 Mixlib::CLI#initialize:

```
=> 156:       klass_options.keys.inject(@options) { |memo, key| memo[key] = klass_options[key].dup; memo }
```

**Comment by siddheshwar-more** [comment]
@cmluciano 

Seems you are bootstrap process using local network IP address (192.168.0.1) during bootstrap.

Could you please also verify that host is reachable with ssh port ( i.e port 22)  ?

**Comment by cmluciano** [comment]
The 192.168.0.1 is a dummy IP I put in place of our real IP. It is a placeholder for the actual public IP. The host is reachable as I can ssh and bootstrap the machine with the regular knife bootstrap command.

**Comment by siddheshwar-more** [comment]
Hello, @cmluciano 
  I've tried same command on https://dashboard.dreamcompute.com/project/instances/  i.e Dream-Host OpenStack setup. And it worked fine for me

I went through again your logs i.e -
:color=>true,
 :editor=>"vim",
 :disable_editing=>false,
 :format=>"summary",
 :ssh_user=>"centos",
**:ssh_port=>5986,**

If you see here **:ssh_port=>5986** is i think wrong value, Please verify your **knife.rb** or command for **ssh_port** value.

**Comment by adamedx** [comment]
@jjasghar , @cmluciano, might be good if you could get together to get a repro, perhaps with @cmluciano's environment. We're at a loss on investigation without a way to repro at the moment.

**Comment by cmluciano** [comment]
@siddheshwar-more was right, it was a ssh_port problem. For some reason it is picking up the port number for winrm in my knife.rb file.

For whatever reason the --ssh-user port is not working, but -p works. I will dig in and try to figure out why it keeps pulling in the winrm_port and setting it as the ssh_port, but this issue is fixed.
