### ISSUE TITLE
Serious Bug with server show instance-id

### ISSUE THREAD

**Issue by b-slim** [chef/knife-openstack#164]
Hey guys i am running into a serious bug with knife-openstack (1.1.0)
The command `bundle exec knife openstack server show --instance-id instance_name` will return a result for any server with a name that has `instance_name` as a suffix.
in my case for instance assuming my server is called `bslim_mysql_server`
And if i run  `bundle exec knife openstack server show --instance-id mysql_server` i will get 
`Instance ID        f5bc2256-6c8e-448a-8f6c-dfca4e463afa
Name               bslim_mysql_server
Flavor             3000
Image              b4001360-4082-4c1e-a307-db1c1c57ee3e
State              ACTIVE
Availability Zone  GridPriv1`

**Comment by jjasghar** [comment]
I don't see this as a bug. I see this as fuzzy matching working.

**Comment by b-slim** [comment]
Hi @jjasghar after looking at the code i figure out that --instance-id is used as a search term https://github.com/chef/knife-openstack/blob/master/lib/chef/knife/cloud/openstack_service.rb#L42.
This is misleading and causing a serious problem in our deploy pipeline.
i am using `^` and `$` for exact matching
