### ISSUE TITLE
1.3.2.pre Release

### ISSUE THREAD

**Issue by jjasghar** [chef/knife-openstack#177]
I'm pushing 1.3.2.pre. Please report and issues or suggestions here. RE: https://github.com/chef/knife-openstack/issues/172

https://github.com/chef/knife-openstack/pull/176

/cc @Cluster444 @b-slim @Vasu1105

**Comment by jjasghar** [comment]
I've released 1.3.2.dev to ruby gems. please get it via:

`gem install knife-openstack --pre`

**Comment by b-slim** [comment]
@jjasghar So far this version is stable, any updates when it will be released ?

**Comment by jjasghar** [comment]
I'll release it today.

**Comment by jjasghar** [comment]
Actually scratch that, I'd like to wait for: https://github.com/chef/knife-openstack/pull/179

**Comment by jjasghar** [comment]
Ok, I'm planning on releasing another pre today. Let it stew for a few days, then i'll push the new gem.

**Comment by jjasghar** [comment]
I just pushed `1.3.2.rc1` to ruby gems.

**Comment by jjasghar** [comment]
Ok, i've verified it every which way. I'm happy with this rc1. As i said above i'll let it stew for a few days then push out the full release in a few days.
