### ISSUE TITLE
Does Knife OpenStack Plugin support nova-networking?

### ISSUE THREAD

**Issue by guoger** [chef/knife-openstack#187]
I'm trying to provision a VM using `knife openstack server create` against a devstack environment with nova-networking. I'm getting errors saying bad network request. So I'm wondering whether nova-networking is supported by knife plugin? I don't have error log at hand but I could fetch it later if necessary.

Thanks in advance!

**Comment by jjasghar** [comment]
Looking at the [README.md](https://github.com/chef/knife-openstack#knife-openstack-network-list) you probably didn't give a network in the command. Though as you said you're using nova-networking, which isn't supported.  Maybe try with neutron, and reopen if you still have an error?

**Comment by guoger** [comment]
@jjasghar thanks! Just wanna confirm about nova-networking before digging further.
